/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check do serviço */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e devolve a sessão (access + refresh token) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova o access token a partir do refresh token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identidade da sessão atual (a partir do access token) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terrenos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista TODOS os terrenos (busca/ordenação ficam no front) */
        get: operations["listTerrenos"];
        put?: never;
        /** Cria um terreno */
        post: operations["createTerreno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terrenos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Atualiza um terreno */
        put: operations["updateTerreno"];
        post?: never;
        /** Remove um terreno */
        delete: operations["deleteTerreno"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria um alvo de upload (presigned POST) pra uma imagem
         * @description Padrão de mercado: o backend NÃO recebe o arquivo. Ele assina um **presigned POST** do S3 e devolve `{ upload, image }`. O cliente faz um `multipart/form-data` POST direto pro `upload.url` com os `upload.fields` + o arquivo (campo `file` por último). Depois do upload, `image` (`{ id, url }`) é o registro que entra em `Terreno.imagens`; `principalId` aponta a principal. O policy do POST trava tamanho (até 5MB) e content-type.
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/resolve-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve um link do Google Maps (inclusive curto) em coordenadas
         * @description O front resolve links COMPLETOS sozinho (parse no navegador). Link CURTO (maps.app.goo.gl) é um redirect que o navegador não segue por falta de CORS — então o backend segue o redirect server-side e extrai lat/lng.
         */
        post: operations["resolveMapsLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        TerrenoImagem: {
            id: string;
            /** Format: uri */
            url: string;
        };
        UploadInput: {
            /**
             * @example image/jpeg
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png" | "image/webp";
        };
        UploadTarget: {
            /** @description Dados do presigned POST do S3. */
            upload: {
                /** Format: uri */
                url: string;
                /** @description Campos do form que vão ANTES do arquivo no multipart. */
                fields: {
                    [key: string]: string;
                };
            };
            image: components["schemas"]["TerrenoImagem"];
        };
        TerrenoInput: {
            /** @example Rua das Palmeiras, 120 */
            rua: string;
            /**
             * @description BRL. Opcional — ausente quando o preço ainda está a negociar.
             * @example 185000
             */
            preco?: number;
            /** @example -22.9056 */
            lat: number;
            /** @example -47.0608 */
            lng: number;
            /**
             * @description m²
             * @example 250
             */
            areaTotal: number;
            /**
             * @description metros
             * @example 10
             */
            largura?: number;
            /**
             * @description metros
             * @example 25
             */
            comprimento?: number;
            /** Format: uri */
            link?: string;
            /**
             * @description Telefone/WhatsApp do contato (opcional). Texto livre — DDI 55 assumido se ausente.
             * @example (45) 99999-0000
             */
            whatsapp?: string;
            imagens?: components["schemas"]["TerrenoImagem"][];
            /** @description id da imagem principal (aparece no pin/tabela/detalhe) */
            principalId?: string;
        };
        Terreno: components["schemas"]["TerrenoInput"] & {
            id: string;
        };
        LoginInput: {
            /** @description identificador de login do usuário; carrega o e-mail. */
            username: string;
            password: string;
        };
        AuthUser: {
            username: string;
        };
        AuthSession: {
            accessToken: string;
            refreshToken: string;
            /**
             * @description segundos até o access token expirar
             * @example 3600
             */
            expiresIn: number;
            user: components["schemas"]["AuthUser"];
        };
        RefreshInput: {
            refreshToken: string;
        };
        AuthTokens: {
            accessToken: string;
            /** @description novo refresh token rotacionado; o anterior é invalidado imediatamente (rotation com grace period 0). */
            refreshToken: string;
            /** @example 3600 */
            expiresIn: number;
        };
        ResolveMapsLinkInput: {
            /** @example https://maps.app.goo.gl/gY6f4xVaTYjQVhzP7 */
            url: string;
        };
        ResolvedLocation: {
            /** @example -22.9056 */
            lat: number;
            /** @example -47.0608 */
            lng: number;
            /** @example Rua das Palmeiras, 120 - Campinas, SP */
            address?: string;
        };
        Error: {
            /** @example Algo deu errado */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serviço no ar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Sessão criada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInput"];
            };
        };
        responses: {
            /** @description Novos access token e refresh token (rotacionado) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Refresh token inválido/expirado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTerrenos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de terrenos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terreno"][];
                };
            };
        };
    };
    createTerreno: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerrenoInput"];
            };
        };
        responses: {
            /** @description Terreno criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terreno"];
                };
            };
            /** @description Dados inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTerreno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerrenoInput"];
            };
        };
        responses: {
            /** @description Terreno atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terreno"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTerreno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInput"];
            };
        };
        responses: {
            /** @description Alvo de upload assinado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTarget"];
                };
            };
            /** @description Content-type não suportado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resolveMapsLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveMapsLinkInput"];
            };
        };
        responses: {
            /** @description Coordenadas resolvidas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedLocation"];
                };
            };
            /** @description Não foi possível extrair coordenadas do link */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
